#### Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
##### a) Addition of 2 in all the element
##### b) Multiply 3 with all the elements
##### c) Divide every element by 2 

In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print("After adding 2 to each element: ",arr+2)
print("After multiplying each element by 3: ",arr*3)
print("After dividing each element by 2: ",arr/2)

After adding 2 to each element:  [3 4 5 6 7]
After multiplying each element by 3:  [ 3  6  9 12 15]
After dividing each element by 2:  [0.5 1.  1.5 2.  2.5]


#### Q.2 Questions on Basic NumPy Array:
##### a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [6]:
arr=np.array([1,2,3,6,4,5])
print("Reversed Array: ",np.flip(arr))

Reversed Array:  [5 4 6 3 2 1]


##### b) Find the most frequent value and their indice(s) in the following arrays:

In [8]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
vals,counts=np.unique(x,return_counts=True)
most_frequent=vals[np.argmax(counts)]
indices=np.where(x==most_frequent)
print(f"Most frequent element: {most_frequent} ")
print(f"Indices of most frequent element: {indices}")

Most frequent element: 1 
Indices of most frequent element: (array([0, 5, 7, 8, 9]),)


In [9]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
vals,counts=np.unique(y,return_counts=True)
most_frequent=vals[np.argmax(counts)]
indices=np.where(y==most_frequent)
print("Most frequent element: ",most_frequent)
print("Indices of most frequent element: ",indices)


Most frequent element:  1
Indices of most frequent element:  (array([0, 1, 2]),)


#### Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
##### a) Access 1st row, 2nd column
##### b) Access 3rd row, 1st column

In [14]:
arr=np.array(([10, 20, 30], [40, 50, 60], [70, 80, 90]))
print("First row, Second column: ",arr[0,1])
print("Third row, First column: ",arr[2,0])

First row, Second column:  20
Third row, First column:  70


#### Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [32]:
siya=np.linspace(10,100,25)
print("Array: ",siya)
print("Dimension of the array: ",np.ndim(siya))
print("Shape of the array: ",np.shape(siya))
print("Total elements: ",np.size(siya))
print("Data type of each element: ",siya.dtype)
print("Total Bytes: ",siya.nbytes)



Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension of the array:  1
Shape of the array:  (25,)
Total elements:  25
Data type of each element:  float64
Total Bytes:  200


In [33]:
print("Reshape using reshape()")
print(siya.reshape(1,25).T)

Reshape using reshape()
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [35]:
print("Reshape using T")
print(siya.T)

Reshape using T
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


##### The T attribute can be used for transposition, but for a 1-D NumPy array, T has no effect. Therefore, the array must first be reshaped into a 2-D array and then transposed.

#### Q5. Create a 2-D Array of three rows and four columns, named ucs420_<\your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<\your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<\your_name>>.

In [37]:
ucs420_siya=np.array(([10,20,30,40],[50,60,70,80],[90,15,20,35]))
print("Array: ",ucs420_siya)
print("Shape of the array: ",np.shape(ucs420_siya))

Array:  [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Shape of the array:  (3, 4)


In [42]:
print("Mean: ",np.mean(ucs420_siya))
print("Median: ",np.median(ucs420_siya))
print("Max element: ",np.max(ucs420_siya))
print("Min element: ",np.min(ucs420_siya))
print("Unique elements: ",np.unique(ucs420_siya))

Mean:  43.333333333333336
Median:  37.5
Max element:  90
Min element:  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]


In [44]:
reshaped_ucs420_siya=ucs420_siya.reshape((4,3))
print("Reshaped Array: ",reshaped_ucs420_siya)

Reshaped Array:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [49]:
resized_ucs420_siya=np.resize(ucs420_siya,(2,3))
print("Resized Array: ",resized_ucs420_siya)

Resized Array:  [[10 20 30]
 [40 50 60]]
